language: python

jobs:
  include:
    - name: "Python 3.9.X on Xenial Linux"
      python: 3.9
      before_install:
        - python -m venv env
        - source env/bin/activate

install: pip install -r requirements