language: python

jobs:
  include:
    - name: "Python 3.9 on Bionic Linux"
      python: 3.9
      os: linux
      dist: xenial
    - name: "Python 3.8 on Bionic Linux"
      python: 3.8
      os: linux
      dist: xenial

install:
  - pip install -r requirements.txt

services:
  - postgresql

script:
  - sh init.sh
  - python main.py test
  - python main.py test_cov