version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-dms
    container_name: employee-dms-app
    command: python main.py gunicorn
    volumes:
      - media_volume:/home/app/employee_dms/src/app/upload/files
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - employee-dms-net

networks:
  employee-dms-net:
    driver: bridge

volumes:
  media_volume: