# This is for test environment

version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: employee-dms-test
    container_name: employee-dms-app-test
    depends_on:
      - db
    command: python main.py test_cov
    ports:
      - "5115:80"
    restart: unless-stopped
    networks:
      - empdms-network-test

  db:
    image: postgres:latest
    container_name: employee-dms-db-test
    environment:
      - POSTGRES_DB=${DATABASE_TEST}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - empdms-network-test

networks:
  empdms-network-test:

volumes:
  postgres_data: