jobs:
  step_one:
    docker:
      - image: circleci/python:3.9
      - image: circleci/postgers:latest
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pip --version
            sh init.sh
            python main.py test
    name: Python 3.9 Requirements
  step_two:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgers:latest
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pip --version
            sh init.sh
            python main.py test
    name: Python 3.8 Requirements

version: 2.1
workflows:
  main:
    jobs:
      - step_one
      - step_two