jobs:
  stepone:
    docker:
      - image: circleci/python:3.9
      - image: circleci/postgers:latest
    steps:
      - checkout
      - run:
          name: Python 3.9 Requirements
          command: |
            pip install -r requirements.txt
            pip --version
            sh init.sh
            python main.py test
  steptwo:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgers:latest
    steps:
      - checkout
      - run:
          name: Python 3.8 Requirements
          command: |
            pip install -r requirements.txt
            pip --version
            sh init.sh
            python main.py test

version: 2.1
workflows:
  main:
    jobs:
      - stepone
      - steptwo