jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            pip --version
          name: Test
orbs:
  python: circleci/python@1.3.4
version: 2.1
workflows:
  main:
    jobs:
      - test