jobs:
  stepone:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_PASSWORD: mypostgre_password
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgersql-client
      - run: whoami
      - run:
          name: Python 3.9 Requirements
          command: |
            pip install -r requirements.txt
            pip --version
            sh init.sh
            python main.py test
            python main.py test_cov
  steptwo:
    docker:
      - image: circleci/python:3.8
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_PASSWORD: mypostgre_password
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run:
          name: Python 3.8 Requirements
          command: |
            pip install -r requirements.txt
            pip --version
            sh init.sh
            python main.py test
            python main.py test_cov

version: 2.1
workflows:
  main:
    jobs:
      - stepone
      - steptwo