jobs:
  test_python39:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pip --version
          name: Test

version: 2.1
workflows:
  main:
    jobs:
      - test_python39